stages:
    - build

build-debian:
    image: registry.videolan.org:5000/dav1d-debian-unstable:20180925105518
    stage: build
    tags:
        - debian
        - amd64
    script:
        - meson build --buildtype release
        - ninja -v -C build
